Divers Hotel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Divers_Hotel.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Divers Hotel/Controllers/Room_UsageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Divers_Hotel.Models;

namespace Divers_Hotel.Controllers
{
    public class Room_UsageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Room_Usage
        public ActionResult Index()
        {
            return View(db.Room_Usage.ToList());
        }

        // GET: Room_Usage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Usage room_Usage = db.Room_Usage.Find(id);
            if (room_Usage == null)
            {
                return HttpNotFound();
            }
            return View(room_Usage);
        }

        // GET: Room_Usage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Room_Usage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Room_Id,Guest_Id,Hours,Checkin,Date")] Room_Usage room_Usage)
        {
            if (ModelState.IsValid)
            {
                db.Room_Usage.Add(room_Usage);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(room_Usage);
        }

        // GET: Room_Usage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Usage room_Usage = db.Room_Usage.Find(id);
            if (room_Usage == null)
            {
                return HttpNotFound();
            }
            return View(room_Usage);
        }

        // POST: Room_Usage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Room_Id,Guest_Id,Hours,Checkin,Date")] Room_Usage room_Usage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room_Usage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(room_Usage);
        }

        // GET: Room_Usage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room_Usage room_Usage = db.Room_Usage.Find(id);
            if (room_Usage == null)
            {
                return HttpNotFound();
            }
            return View(room_Usage);
        }

        // POST: Room_Usage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room_Usage room_Usage = db.Room_Usage.Find(id);
            db.Room_Usage.Remove(room_Usage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Divers Hotel/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    This program was built by <i>Mr. Chris</i> as a simple Hotel Management System. <br />
    It was developed using C# with Entity framework code-first approach.
    This could be expanded by adding extra features like payment options and report printing.
    I have already expanded this to include payment, star based reviews and report printing.
    Contact me if need be.
    This particular source code is free, remember to subscribe to my youtube channel for updates and other free
    tutorials and their source codes. Checkout the about page for my contact details.
</p>

Divers Hotel/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    Lagos NGR<br />
    <abbr title="Phone">Phone:</abbr>
    +234.816.027.4007
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:ngcodes1@gmail.com">ngcodes1@gmail.com</a><br />
    <strong>Fiverr.com:</strong> <a href="https://www.fiverr.com/loveth01">Fiverr</a><br />
    <strong>YouTube:</strong> <a href="https://www.youtube.com/channel/UCaUUBHLa2zEOiJVj7_-hnmQ">YouTube</a>
</address>

Divers Hotel/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-height:20em">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" style="max-height:20em">
            <div class="item active">
                <img src="~/Images/Hotels Rooms/premiere 1_1920x960.jpg" alt="Chania" class="center-block" style="max-height:20em">
                <div class="carousel-caption top">
                    <h3>VIP Rooms</h3>
                    <p>Get VIP Rooms with so much fun!</p>
                </div>
            </div>

            <div class="item">
                <img src="~/Images/bicycle-3045580__480.jpg" class="center-block" alt="Chicago" style="max-height:20em">
                <div class="carousel-caption">
                    <h3>Rush Now</h3>
                    <p>Get the best of comfort!</p>
                </div>
            </div>

            <div class="item">
                <img src="~/Images/winning-back-a-client.jpg" class="center-block" alt="New York" style="max-height:20em">
                <div class="carousel-caption">
                    <h3>Customer Satisfaction?</h3>
                    <p>We love every customer and will do the best to serve you better.</p>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-4 fa-border"
         style="background-color:lightgray; border-width:1em">
        <h2>Getting started</h2>
        <p>
            Create Account in a few simple steps and become eligible to book the best rooms.
        </p>
        <p>@Html.ActionLink("Get Started", "Register", "Account")</p><br />
    </div>
    <div class="col-md-4 fa-border"
         style="background-color:lightblue; border-width:1em">
        <h2>Book Available Rooms</h2>
        <p>Only available rooms can be booked. Click to secure a room for your self and experience the best of luxuries.</p>
        <p>@Html.ActionLink("Am Interested!", "Create", "Room_Usage")</p><br />
    </div>
    <div class="col-md-4 fa-border"
         style="background-color:lightgray; border-width:1em">
        <h2>Booking History</h2>
        <p>View your history and explore your past lodgings. We have an advance search with which you can query your history with us.</p>
        <p>@Html.ActionLink("Am Interested!", "Index", "Room_Usage")</p>
    </div>
</div>